import { CASE_STATUS_VALUES, EVENT_STATUS_VALUES, LEAD_STATUS_VALUES, TASK_STATUS_VALUES } from '../domain-statuses';
import { CLIENT_HEALTH_OPTIONS, CLIENT_SOURCE_OPTIONS, PORTAL_STATUS_OPTIONS } from './client-options';
import { COMMISSION_STATUSES, PAYMENT_STATUSES } from '../finance/finance-types.js';

export type StatusSourceKind = 'source' | 'derived' | 'ui-only' | 'legacy';
export type StatusMeta = { value: string; label: string; source: StatusSourceKind; entity: string; readOnly?: boolean };
export type StatusRepositorySection = { entity: string; sourceFiles: readonly string[]; importedOrAdapted: string; notDuplicated: string; source: boolean; derived: boolean; uiOnly: boolean; legacy: boolean; legacyAliases: Readonly<Record<string,string>>; closedValues: readonly string[]; labels: Readonly<Record<string,string>>; tones: Readonly<Record<string,string>>; items: readonly StatusMeta[]; contract: string };

const src = {
  domain: 'src/lib/domain-statuses.ts', lead: 'src/lib/source-of-truth/lead-options.ts', client: 'src/lib/source-of-truth/client-options.ts', case: 'src/lib/source-of-truth/case-options.ts', schedule: 'src/lib/source-of-truth/schedule-options.ts', financeTypes: 'src/lib/finance/finance-types.ts', financeNormalize: 'src/lib/finance/finance-normalize.ts', caseFinance: 'src/lib/finance/case-finance-source.ts', ownerMissing: 'src/lib/owner-control/owner-control-missing-blockers.ts', ownerBaseline: 'src/lib/owner-control/owner-control-baseline.ts', lifecycle: 'src/lib/case-lifecycle-v1.ts', activity: 'src/lib/activity-timeline.ts'
} as const;
const make = (values: readonly string[], entity: string, source: StatusSourceKind, readOnly = false): StatusMeta[] => values.map((value) => ({ value, label: value === 'done' && entity === 'event' ? 'Odbyte' : value, source, entity, readOnly }));
const section = (entity: string, files: readonly string[], items: readonly StatusMeta[], flags: Pick<StatusRepositorySection,'source'|'derived'|'uiOnly'|'legacy'>, contract: string, legacyAliases: Record<string,string> = {}, closedValues: readonly string[] = []): StatusRepositorySection => ({ entity, sourceFiles: files, importedOrAdapted: files.join(' + '), notDuplicated: contract, ...flags, legacyAliases, closedValues, labels: Object.fromEntries(items.map((item) => [item.value, item.label])), tones: {}, items, contract });

export const leadStatus = section('lead', [src.domain, src.lead], make(LEAD_STATUS_VALUES, 'lead', 'source'), {source:true, derived:false, uiOnly:false, legacy:true}, 'adapted from existing lead sources', {follow_up:'waiting_response', active_service:'moved_to_service'}, ['won','lost','moved_to_service','archived']);
export const clientHealthStatus = section('client.health', [src.client], CLIENT_HEALTH_OPTIONS.map((x) => ({value:x.value,label:x.label,source:'derived',entity:'client.health',readOnly:true})), {source:false, derived:true, uiOnly:false, legacy:false}, 'clientHealth !== clientSource !== portalStatus');
export const clientSourceStatus = section('client.source', [src.client], CLIENT_SOURCE_OPTIONS.map((x) => ({value:x.value,label:x.label,source:'source',entity:'client.source'})), {source:true, derived:false, uiOnly:false, legacy:false}, 'clientHealth !== clientSource !== portalStatus');
export const clientPortalStatus = section('client.portal', [src.client], PORTAL_STATUS_OPTIONS.map((x) => ({value:x.value,label:x.label,source:'derived',entity:'client.portal',readOnly:true})), {source:false, derived:true, uiOnly:false, legacy:false}, 'clientHealth !== clientSource !== portalStatus');
export const caseStatus = section('case', [src.domain, src.case], make(CASE_STATUS_VALUES, 'case', 'source'), {source:true, derived:false, uiOnly:false, legacy:true}, 'case.status !== caseLifecycle.bucket', {closed:'completed',done:'completed'}, ['completed','done','closed','archived','canceled','cancelled']);
export const caseLifecycleStatus = section('case.lifecycle', [src.lifecycle], make(['blocked','waiting_approval','ready_to_start','in_progress','completed','needs_next_step'], 'case.lifecycle', 'derived', true), {source:false, derived:true, uiOnly:false, legacy:false}, 'case.status !== caseLifecycle.bucket', {}, ['completed']);
export const taskStatus = section('task', [src.domain, src.schedule], make(TASK_STATUS_VALUES, 'task', 'source'), {source:true, derived:false, uiOnly:false, legacy:true}, 'task.done !== event.done', {open:'todo',completed:'done'}, ['done','completed','cancelled','canceled','archived','deleted']);
export const eventStatus = section('event', [src.domain, src.schedule], make(EVENT_STATUS_VALUES, 'event', 'source'), {source:true, derived:false, uiOnly:false, legacy:true}, 'task.done !== event.done', {planned:'scheduled',completed:'done'}, ['done','completed','cancelled','canceled','deleted']);
export const paymentStatus = section('payment', [src.financeTypes, src.financeNormalize, src.caseFinance], make(PAYMENT_STATUSES, 'payment', 'source'), {source:true, derived:false, uiOnly:false, legacy:true}, 'payment.status !== payment.paidLikeCompatibility', {pending:'due',awaiting_payment:'due',settled:'paid'}, ['paid','cancelled']);
export const paidLikeCompatibilityValues = ['paid','fully_paid','deposit_paid','partially_paid','confirmed','settled','completed','done'] as const;
export const dueLikeCompatibilityValues = ['due','planned','pending','awaiting_payment','open'] as const;
export const missingItemStatus = section('missing-item', [src.ownerMissing, src.activity, src.case], make(['missing_item','blocking_missing_item','blocksProgress'], 'missing-item', 'source'), {source:true, derived:true, uiOnly:false, legacy:true}, 'active missing source record is task/work-item, not activity history', {missing:'missing_item'}, ['resolved','deleted','done','completed','closed','cancelled','canceled','archived']);
export const ownerControlStatus = section('owner-control', [src.ownerBaseline, src.ownerMissing], make(['critical','warning','normal'], 'owner-control', 'derived', true), {source:false, derived:true, uiOnly:false, legacy:false}, 'Owner Control is derived consumer, not source');
export const activityStatus = section('activity', [src.activity], make(['status','task','event','missing_item','payment','billing','lead_moved'], 'activity', 'ui-only'), {source:false, derived:false, uiOnly:true, legacy:false}, 'activity is UI-only timeline formatting');
export const commissionStatus = section('commission', [src.financeTypes, src.financeNormalize, src.caseFinance], make(COMMISSION_STATUSES, 'commission', 'derived', true), {source:false, derived:true, uiOnly:false, legacy:true}, 'commissionStatus = derived/read-only, not manual select', {commission_pending:'expected'}, ['paid']);
export const statusRepository = {leadStatus,clientHealthStatus,clientSourceStatus,clientPortalStatus,caseStatus,caseLifecycleStatus,taskStatus,eventStatus,paymentStatus,missingItemStatus,ownerControlStatus,activityStatus,commissionStatus} as const;
export const STATUS_REPOSITORY_SOURCE_MAP = Object.fromEntries(Object.entries(statusRepository).map(([k,v]) => [k,{entity:v.entity,sourceFile:v.sourceFiles.join(' + '),importedOrAdapted:v.importedOrAdapted,notDuplicated:v.notDuplicated,derivedUiOnlyLegacyHandling:{source:v.source,derived:v.derived,uiOnly:v.uiOnly,legacy:v.legacy,legacyAliases:v.legacyAliases}}]));
