const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

test('FRT-012 renders the populated Lead Edit modal with canonical fields and real data bindings', () => {
  const leadDetail = read('src/pages/LeadDetail.tsx');
  const apiLeads = read('api/leads.ts');
  const dialogCss = read('src/styles/owners/closeflow-dialogs.css');
  const contract = read('_project/contracts/forteca-clean/FRT-012_LEAD_EDIT.md');

  assert.match(contract, /STAGE_ID: FRT-012/);
  assert.match(contract, /TARGET_ROUTE: \/leads\/:leadId/);
  assert.match(contract, /Edit Lead modal/);
  assert.match(leadDetail, /data-forteca-frt-012-lead-edit="true"/);
  assert.match(leadDetail, /data-forteca-frt-012-form="true"/);
  assert.match(leadDetail, /Edytuj leada/);
  assert.match(leadDetail, /Nazwa leada <span aria-hidden="true">\*<\/span>/);
  assert.match(leadDetail, /Firma <span aria-hidden="true">\*<\/span>/);
  assert.match(leadDetail, /Kontakt główny/);
  assert.match(leadDetail, /Imię i nazwisko/);
  assert.match(leadDetail, /Stanowisko/);
  assert.match(leadDetail, /E-mail <span aria-hidden="true">\*<\/span>/);
  assert.match(leadDetail, /Telefon/);
  assert.match(leadDetail, /Status <span aria-hidden="true">\*<\/span>/);
  assert.match(leadDetail, /Wartość <span aria-hidden="true">\*<\/span>/);
  assert.match(leadDetail, /Priorytet <span aria-hidden="true">\*<\/span>/);
  assert.match(leadDetail, /Źródło <span aria-hidden="true">\*<\/span>/);
  assert.match(leadDetail, /Ostatni kontakt/);
  assert.match(leadDetail, /Następny krok <span aria-hidden="true">\*<\/span>/);
  assert.match(leadDetail, /Termin <span aria-hidden="true">\*<\/span>/);
  assert.match(leadDetail, /Opiekun <span aria-hidden="true">\*<\/span>/);
  assert.match(leadDetail, /Notatka handlowa/);
  assert.ok(leadDetail.includes('value={editLead?.summary || \'\'}'));
  assert.ok(leadDetail.includes('value={editLead?.company || \'\'}'));
  assert.ok(leadDetail.includes('value={editLead?.name || \'\'}'));
  assert.ok(leadDetail.includes('value={editLead?.email ?? \'\'}'));
  assert.ok(leadDetail.includes('value={editLead?.phone ?? \'\'}'));
  assert.match(leadDetail, /email: asText\(lead\.email\)/);
  assert.match(leadDetail, /phone: asText\(lead\.phone\)/);
  assert.ok(leadDetail.includes('value={editLead?.dealValue ?? \'\'}'));
  assert.ok(leadDetail.includes('value={editLead?.nextActionTitle || \'\'}'));
  assert.match(leadDetail, /type="date"/);
  assert.match(leadDetail, /id="forteca-frt-012-lead-summary"[\s\S]*?required/);
  assert.match(leadDetail, /id="forteca-frt-012-company"[\s\S]*?required/);
  assert.match(leadDetail, /id="forteca-frt-012-email"[\s\S]*?required/);
  assert.match(leadDetail, /id="forteca-frt-012-next-action-title"[\s\S]*?required/);
  assert.match(leadDetail, /id="forteca-frt-012-next-action-date"[\s\S]*?required/);
  assert.match(leadDetail, /maxLength=\{2000\}/);
  assert.match(leadDetail, /String\(editLead\?\.notes \|\| editLead\?\.note \|\| ''\)\.length/);
  assert.match(leadDetail, /LEAD_STATUS_OPTIONS\.map/);
  assert.match(leadDetail, /LEAD_SOURCE_OPTIONS\.map/);
  assert.match(leadDetail, /PRIORITY_OPTIONS\.map/);
  assert.match(leadDetail, /TASK_TYPES\.map/);
  assert.match(leadDetail, /readOnly/);
  assert.match(leadDetail, /data-forteca-frt-012-readonly-field="position"/);
  assert.match(leadDetail, /data-forteca-frt-012-readonly-field="last-contact"/);
  assert.match(leadDetail, /data-forteca-frt-012-readonly-field="owner"/);
  assert.match(leadDetail, /const handleLeadEditOpenChange = \(open: boolean\)/);
  assert.match(leadDetail, /onOpenChange={handleLeadEditOpenChange}/);
  assert.match(leadDetail, /const handleMoveLeadToCaseFromEdit = \(\)/);
  assert.match(leadDetail, /handleDeleteLead/);
  assert.match(leadDetail, /handleUpdateLead/);
  assert.match(leadDetail, /summary: editLead\.summary/);
  assert.match(leadDetail, /notes: editLead\.notes/);
  assert.match(leadDetail, /priority: editLead\.priority/);
  assert.match(leadDetail, /nextActionTitle: editLead\.nextActionTitle/);
  assert.match(leadDetail, /nextActionAt: editLead\.nextActionAt/);
  assert.match(apiLeads, /if \(body\.summary !== undefined\) payload\.summary/);
  assert.match(apiLeads, /body\.notes !== undefined \|\| body\.note !== undefined/);
  assert.match(apiLeads, /if \(body\.priority !== undefined\)/);
  assert.match(dialogCss, /FRT-012 — Forteca calm-light populated Lead edit modal/);
  assert.match(dialogCss, /data-forteca-frt-012-lead-edit="true"/);
  assert.match(dialogCss, /\.forteca-frt-012-footer button\.forteca-frt-012-delete/);
  assert.doesNotMatch(dialogCss, /#root[^\n]*data-forteca-frt-012/);
});

test('FRT-012 preserves existing values, derives legacy optional fields truthfully and avoids fixture data', () => {
  const leadDetail = read('src/pages/LeadDetail.tsx');
  assert.match(leadDetail, /summary: lead\.summary \|\| lead\.title \|\| lead\.name \|\| ''/);
  assert.match(leadDetail, /notes: lead\.notes \|\| lead\.note \|\| leadPrimaryNoteText \|\| ''/);
  assert.match(leadDetail, /nextActionTitle: lead\.nextActionTitle \|\| lead\.next_action_title \|\| nextTimelineEntry\?\.title/);
  assert.match(leadDetail, /toOptionalLocalDateTime\(lead\.nextActionAt \|\| lead\.next_action_at \|\| nextTimelineEntry\?\.dateValue\)/);
  assert.match(leadDetail, /setIsEditing\(false\)/);
  assert.match(leadDetail, /if \(!open\) \{/);
  assert.match(leadDetail, /setLeadEditSaving\(false\)/);
  assert.match(leadDetail, /Brak danych w rekordzie/);
  assert.doesNotMatch(leadDetail, /ACME Logistics|Jan Kowalski|Damian Knapik/);
});
