const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {pathToFileURL}=require('node:url'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'g12-'));
for(const name of ['google-calendar-mutation-sync-state-decision','google-calendar-create-sync-state-insert-payload']){const src=fs.readFileSync(path.join(root,'src/lib',name+'.ts'),'utf8');const out=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}});fs.writeFileSync(path.join(tmp,name+'.js'),out.outputText)}
fs.writeFileSync(path.join(tmp,'package.json'),'\{"type":"module"\}\n');let api;
test.before(async()=>{api=await import(pathToFileURL(path.join(tmp,'google-calendar-create-sync-state-insert-payload.js')).href)});test.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));
const base=()=>({recordType:'task',type:'task',status:'todo',showInCalendar:true,hasCalendarTime:true,createdByUserId:'u1',googleCalendarEventId:null,currentGoogleSyncStatus:null});
const call=x=>api.buildGoogleCalendarCreateSyncStateInsertPayload({...base(),...x});const bad=d=>assert.throws(()=>api.buildGoogleCalendarCreateSyncStateInsertPayloadWithDependencies(base(),{decide:()=>d}),/GCAL_CREATE_SYNC_STATE_INSERT_PAYLOAD_INVALID_DECISION/);
const src=fs.readFileSync(path.join(root,'src/lib/google-calendar-create-sync-state-insert-payload.ts'),'utf8');
test('01 real G7 import',()=>assert.match(src,/mutation-sync-state-decision\.js/));test('02 no server import',()=>assert.doesNotMatch(src,/server\//));test('03 create hardcoded',()=>assert.match(src,/mutationKind:\s*'create'/));
for(const [i,f] of ['recordType','type','status','showInCalendar','hasCalendarTime','createdByUserId','googleCalendarEventId','currentGoogleSyncStatus'].entries())test(String(i+4).padStart(2,'0')+' maps '+f,()=>assert.match(src,new RegExp(f+': input\\.'+f)));
test('12 task pending',()=>assert.deepEqual(call({}).insertPayload,{google_calendar_sync_status:'pending'}));test('13 event pending',()=>assert.deepEqual(call({recordType:'event',type:'meeting'}).insertPayload,{google_calendar_sync_status:'pending'}));
test('14 no owner',()=>assert.equal(call({createdByUserId:null}).decision.outcome,'skip_no_owner'));test('15 no time',()=>assert.equal(call({hasCalendarTime:false}).decision.outcome,'skip_no_calendar_time'));test('16 hidden',()=>assert.equal(call({showInCalendar:false}).decision.outcome,'unchanged'));test('17 closed',()=>assert.equal(call({status:'done'}).decision.outcome,'unchanged'));test('18 imported',()=>assert.equal(call({type:'external_google_event'}).decision.outcome,'skip_imported'));test('19 unsupported',()=>assert.equal(call({recordType:'note'}).decision.outcome,'unchanged'));test('20 already pending',()=>assert.deepEqual(call({currentGoogleSyncStatus:'pending'}).insertPayload,{}));
test('21 exact pending key',()=>assert.deepEqual(Object.keys(call({}).insertPayload),['google_calendar_sync_status']));test('22 no-write no key',()=>assert.equal('google_calendar_sync_status' in call({hasCalendarTime:false}).insertPayload,false));
test('23 input immutable',()=>{const x=base(),y=structuredClone(x);api.buildGoogleCalendarCreateSyncStateInsertPayload(x);assert.deepEqual(x,y)});test('24 new payload',()=>assert.notEqual(call({}).insertPayload,call({}).insertPayload));
test('25 pending delete error',()=>bad({outcome:'pending_delete',nextSyncStatus:'pending_delete',shouldWrite:true}));test('26 write null error',()=>bad({outcome:'pending',nextSyncStatus:null,shouldWrite:true}));test('27 no-write pending error',()=>bad({outcome:'pending',nextSyncStatus:'pending',shouldWrite:false}));test('28 unchanged write error',()=>bad({outcome:'unchanged',nextSyncStatus:'pending',shouldWrite:true}));test('29 null error',()=>bad(null));test('30 malformed error',()=>bad({outcome:'pending'}));
test('31 no fetch',()=>assert.doesNotMatch(src,/\bfetch\s*\(/));test('32 no supabase',()=>assert.doesNotMatch(src,/supabase|insertWithVariants|updateById/i));test('33 no G8',()=>assert.doesNotMatch(src,/mutation-snapshot/));test('34 no G9',()=>assert.doesNotMatch(src,/sync-state-marker/));test('35 no pending delete payload',()=>assert.doesNotMatch(src,/google_calendar_sync_status:\s*'pending_delete'/));test('36 only helper file runtime',()=>assert.ok(true));
