import type { AppSnapshot, CaseTemplate, TemplateItem } from "./types"
import { addDaysAt, createId } from "./utils"

function createBaseSnapshot(): Omit<AppSnapshot, "leads" | "items"> {
  return {
    user: {
      name: "Twoje konto",
      email: "",
    },
    context: {
      userId: null,
      workspaceId: null,
      accessStatus: "local",
      billingStatus: "local",
    },
    billing: {
      planName: "Solo",
      status: "trial",
      renewAt: addDaysAt(7, 10, 0),
      trialEndsAt: addDaysAt(7, 10, 0),
      canCreate: true,
    },
    settings: {
      timezone: "Europe/Warsaw",
      inAppReminders: true,
      emailReminders: false,
      defaultReminder: "1h_before",
      defaultSnooze: "tomorrow",
      workspaceName: "ClientPilot",
      fontScale: "compact",
      viewProfile: "desktop",
      theme: "classic",
    },
  }
}

const oldLead = (daysAgo: number) => addDaysAt(-daysAgo, 10, 0)

const today09 = addDaysAt(0, 9, 0)
const today11 = addDaysAt(0, 11, 0)
const today15 = addDaysAt(0, 15, 0)
const yesterday10 = addDaysAt(-1, 10, 0)
const twoDaysAgo12 = addDaysAt(-2, 12, 0)
const tomorrow14 = addDaysAt(1, 14, 0)
const tomorrow16 = addDaysAt(1, 16, 0)
const inTwoDays11 = addDaysAt(2, 11, 0)
const inThreeDays10 = addDaysAt(3, 10, 0)
const createdOld = addDaysAt(-8, 8, 0)

function createDefaultTemplates(now: string): { caseTemplates: CaseTemplate[]; templateItems: TemplateItem[] } {
  const templates: CaseTemplate[] = [
    {
      id: "tpl_website",
      workspaceId: "workspace_local",
      createdByUserId: null,
      code: "website_start",
      title: "Strona www",
      description: "Start realizacji strony www: materiały, dostęp i akceptacje.",
      serviceType: "website",
      isDefault: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_branding",
      workspaceId: "workspace_local",
      createdByUserId: null,
      code: "branding_start",
      title: "Branding",
      description: "Proces brandingu od briefu po akceptację wariantu.",
      serviceType: "branding",
      isDefault: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_ads",
      workspaceId: "workspace_local",
      createdByUserId: null,
      code: "ads_campaign_start",
      title: "Kampania reklamowa",
      description: "Checklista uruchomienia kampanii reklamowej.",
      serviceType: "ads_campaign",
      isDefault: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_onboarding",
      workspaceId: "workspace_local",
      createdByUserId: null,
      code: "client_onboarding_start",
      title: "Onboarding klienta",
      description: "Szybkie wejście klienta do współpracy po sprzedaży.",
      serviceType: "client_onboarding",
      isDefault: true,
      createdAt: now,
      updatedAt: now,
    },
  ]

  const items: TemplateItem[] = [
    {
      id: "tpl_item_website_100",
      workspaceId: "workspace_local",
      templateId: "tpl_website",
      createdByUserId: null,
      sortOrder: 100,
      kind: "file",
      title: "Prześlij logo i księgę znaku",
      description: "Wymagane pliki źródłowe logo.",
      required: true,
      defaultDueOffsetDays: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_website_200",
      workspaceId: "workspace_local",
      templateId: "tpl_website",
      createdByUserId: null,
      sortOrder: 200,
      kind: "access",
      title: "Dostęp do hostingu / domeny",
      description: "Dane administracyjne lub zaproszenie.",
      required: true,
      defaultDueOffsetDays: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_website_300",
      workspaceId: "workspace_local",
      templateId: "tpl_website",
      createdByUserId: null,
      sortOrder: 300,
      kind: "approval",
      title: "Akceptacja makiety",
      description: "Potwierdzenie kierunku strony.",
      required: true,
      defaultDueOffsetDays: 5,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_branding_100",
      workspaceId: "workspace_local",
      templateId: "tpl_branding",
      createdByUserId: null,
      sortOrder: 100,
      kind: "response",
      title: "Odpowiedzi na brief strategiczny",
      description: "Uzupełniony brief brandingowy.",
      required: true,
      defaultDueOffsetDays: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_branding_200",
      workspaceId: "workspace_local",
      templateId: "tpl_branding",
      createdByUserId: null,
      sortOrder: 200,
      kind: "decision",
      title: "Wybór kierunku wizualnego",
      description: "Decyzja klienta między wariantami.",
      required: true,
      defaultDueOffsetDays: 4,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_branding_300",
      workspaceId: "workspace_local",
      templateId: "tpl_branding",
      createdByUserId: null,
      sortOrder: 300,
      kind: "file",
      title: "Przesłanie referencji / inspiracji",
      description: "Materiały pomocnicze od klienta.",
      required: false,
      defaultDueOffsetDays: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_ads_100",
      workspaceId: "workspace_local",
      templateId: "tpl_ads",
      createdByUserId: null,
      sortOrder: 100,
      kind: "access",
      title: "Dostęp do kont reklamowych",
      description: "Meta/Google Ads z odpowiednimi rolami.",
      required: true,
      defaultDueOffsetDays: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_ads_200",
      workspaceId: "workspace_local",
      templateId: "tpl_ads",
      createdByUserId: null,
      sortOrder: 200,
      kind: "file",
      title: "Materiały kreatywne",
      description: "Grafiki i copy pod kampanię.",
      required: true,
      defaultDueOffsetDays: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_ads_300",
      workspaceId: "workspace_local",
      templateId: "tpl_ads",
      createdByUserId: null,
      sortOrder: 300,
      kind: "approval",
      title: "Akceptacja konfiguracji kampanii",
      description: "Finalne zielone światło przed startem.",
      required: true,
      defaultDueOffsetDays: 3,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_onboarding_100",
      workspaceId: "workspace_local",
      templateId: "tpl_onboarding",
      createdByUserId: null,
      sortOrder: 100,
      kind: "response",
      title: "Wypełnienie formularza onboardingowego",
      description: "Dane kontaktowe i cele współpracy.",
      required: true,
      defaultDueOffsetDays: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_onboarding_200",
      workspaceId: "workspace_local",
      templateId: "tpl_onboarding",
      createdByUserId: null,
      sortOrder: 200,
      kind: "access",
      title: "Nadanie dostępów zespołowi",
      description: "Kluczowe narzędzia i konta.",
      required: true,
      defaultDueOffsetDays: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tpl_item_onboarding_300",
      workspaceId: "workspace_local",
      templateId: "tpl_onboarding",
      createdByUserId: null,
      sortOrder: 300,
      kind: "decision",
      title: "Akceptacja planu startowego",
      description: "Potwierdzenie zakresu i kolejnych kroków.",
      required: true,
      defaultDueOffsetDays: 3,
      createdAt: now,
      updatedAt: now,
    },
  ]

  return { caseTemplates: templates, templateItems: items }
}

export function createInitialSnapshot(): AppSnapshot {
  const now = new Date().toISOString()
  const defaults = createDefaultTemplates(now)
  return {
    ...createBaseSnapshot(),
    leads: [],
    items: [],
    caseTemplates: defaults.caseTemplates,
    templateItems: defaults.templateItems,
    cases: [],
    caseItems: [],
    contacts: [],
    activityLog: [],
    clientPortalTokens: [],
    approvals: [],
    notifications: [],
    fileAttachments: [],
  }
}

export function createDemoSnapshot(): AppSnapshot {
  const now = new Date().toISOString()
  const defaults = createDefaultTemplates(now)
  return {
    ...createBaseSnapshot(),
    context: {
      ...createBaseSnapshot().context,
      seedKind: "demo",
    },
    user: {
      name: "Demo",
      email: "demo@example.com",
    },
    caseTemplates: defaults.caseTemplates,
    templateItems: defaults.templateItems,
    cases: [],
    caseItems: [],
    contacts: [],
    activityLog: [],
    clientPortalTokens: [],
    approvals: [],
    notifications: [],
    fileAttachments: [],
    leads: [
      {
        id: "lead_1",
        name: "Marcin Kowalski",
        company: "TechFlow Sp. z o.o.",
        email: "marcin@techflow.pl",
        phone: "+48 600 123 456",
        source: "LinkedIn",
        value: 8500,
        summary: "Zainteresowany pakietem Enterprise.",
        notes: "Czeka na ofertę i szybki follow-up.",
        status: "follow_up",
        priority: "high",
        nextActionTitle: "Odpisać na wiadomość",
        nextActionAt: today11,
        nextActionItemId: null,
        createdAt: createdOld,
        updatedAt: oldLead(7),
      },
      {
        id: "lead_2",
        name: "Ania Nowak",
        company: "Nowak Design Studio",
        email: "ania@nowakdesign.pl",
        phone: "+48 512 987 654",
        source: "Polecenie",
        value: 3200,
        summary: "Szykuje rebranding i nową stronę.",
        notes: "Po rozmowie trzeba domknąć brief.",
        status: "qualification",
        priority: "high",
        nextActionTitle: "Przygotować brief",
        nextActionAt: today09,
        nextActionItemId: null,
        createdAt: createdOld,
        updatedAt: addDaysAt(-1, 12, 0),
      },
      {
        id: "lead_3",
        name: "Piotr Zając",
        company: "Zając Consulting",
        email: "piotr@zajac.pl",
        phone: "+48 601 555 321",
        source: "Strona www",
        value: 5000,
        summary: "Oferta wysłana, brak odpowiedzi.",
        notes: "Wymaga szybkiego telefonu follow-up.",
        status: "offer_sent",
        priority: "medium",
        nextActionTitle: "Zadzwonić w sprawie oferty",
        nextActionAt: yesterday10,
        nextActionItemId: null,
        createdAt: createdOld,
        updatedAt: oldLead(8),
      },
      {
        id: "lead_4",
        name: "Karolina Wiśniewska",
        company: "Wiśniewska PR",
        email: "karolina@wisniewska.pl",
        phone: "+48 798 111 222",
        source: "LinkedIn",
        value: 2800,
        summary: "Wstępne zainteresowanie social media.",
        notes: "Trzeba wrócić z prostą propozycją.",
        status: "new",
        priority: "medium",
        nextActionTitle: "Pierwsza wiadomość",
        nextActionAt: tomorrow16,
        nextActionItemId: null,
        createdAt: createdOld,
        updatedAt: oldLead(6),
      },
      {
        id: "lead_5",
        name: "Tomasz Błaszczyk",
        company: "Błaszczyk IT Solutions",
        email: "tomasz@blaszczyk.pl",
        phone: "+48 501 777 888",
        source: "Cold outreach",
        value: 12000,
        summary: "Duży projekt migracji danych.",
        notes: "Kluczowy lead miesiąca.",
        status: "new",
        priority: "high",
        nextActionTitle: "Rozmowa wstępna",
        nextActionAt: today15,
        nextActionItemId: null,
        createdAt: createdOld,
        updatedAt: oldLead(6),
      },
      {
        id: "lead_6",
        name: "Monika Jabłońska",
        company: "Jabłońska Finanse",
        email: "monika@jablonska.pl",
        phone: "+48 609 444 555",
        source: "Polecenie",
        value: 1500,
        summary: "Chce demo w przyszłym tygodniu.",
        notes: "Odpisała już na maila.",
        status: "contacted",
        priority: "low",
        nextActionTitle: "Demo dla Moniki",
        nextActionAt: inTwoDays11,
        nextActionItemId: null,
        createdAt: createdOld,
        updatedAt: oldLead(6),
      },
      {
        id: "lead_7",
        name: "Agata Szymańska",
        company: "Szymańska Legal",
        email: "agata@szymanska.pl",
        phone: "+48 511 888 999",
        source: "Strona www",
        value: 6500,
        summary: "Podpisana umowa.",
        notes: "Projekt startuje w połowie miesiąca.",
        status: "won",
        priority: "high",
        nextActionTitle: "Start projektu",
        nextActionAt: inTwoDays11,
        nextActionItemId: null,
        createdAt: createdOld,
        updatedAt: addDaysAt(-2, 11, 0),
      },
      {
        id: "lead_8",
        name: "Sylwia Kowalczyk",
        company: "Kowalczyk E-commerce",
        email: "sylwia@kowalczyk.pl",
        phone: "+48 505 333 444",
        source: "Polecenie",
        value: 9500,
        summary: "Szukają wsparcia w Google Ads.",
        notes: "Po rozmowie trzeba wysłać case studies.",
        status: "contacted",
        priority: "high",
        nextActionTitle: "Wysłać case studies",
        nextActionAt: twoDaysAgo12,
        nextActionItemId: null,
        createdAt: createdOld,
        updatedAt: oldLead(6),
      },
    ],
    items: [
      {
        id: createId("item"),
        leadId: "lead_1",
        recordType: "task",
        type: "follow_up",
        title: "Odpisać na wiadomość Marcina",
        description: "Czeka na szczegóły oferty Enterprise.",
        status: "todo",
        priority: "high",
        scheduledAt: today11,
        startAt: "",
        endAt: "",
        recurrence: "none",
        reminder: "1h_before",
        createdAt: createdOld,
        updatedAt: today11,
        showInTasks: true,
        showInCalendar: true,
      },
      {
        id: createId("item"),
        leadId: "lead_1",
        recordType: "event",
        type: "meeting",
        title: "Demo systemu — Marcin",
        description: "Google Meet, link wysłany mailem.",
        status: "todo",
        priority: "high",
        scheduledAt: "",
        startAt: tomorrow14,
        endAt: addDaysAt(1, 14, 30),
        recurrence: "none",
        reminder: "1h_before",
        createdAt: createdOld,
        updatedAt: tomorrow14,
        showInTasks: true,
        showInCalendar: true,
      },
      {
        id: createId("item"),
        leadId: "lead_2",
        recordType: "task",
        type: "task",
        title: "Przygotować brief rebrandingowy",
        description: "Na podstawie rozmowy z Anią.",
        status: "todo",
        priority: "high",
        scheduledAt: today09,
        startAt: "",
        endAt: "",
        recurrence: "none",
        reminder: "at_time",
        createdAt: createdOld,
        updatedAt: today09,
        showInTasks: true,
        showInCalendar: false,
      },
      {
        id: createId("item"),
        leadId: "lead_3",
        recordType: "task",
        type: "deadline",
        title: "Zadzwonić w sprawie oferty",
        description: "Brak odpowiedzi po 4 dniach.",
        status: "todo",
        priority: "medium",
        scheduledAt: yesterday10,
        startAt: "",
        endAt: "",
        recurrence: "none",
        reminder: "1h_before",
        createdAt: createdOld,
        updatedAt: yesterday10,
        showInTasks: true,
        showInCalendar: true,
      },
      {
        id: createId("item"),
        leadId: "lead_5",
        recordType: "event",
        type: "call",
        title: "Rozmowa wstępna — Tomasz",
        description: "15 minut, telefon.",
        status: "todo",
        priority: "high",
        scheduledAt: "",
        startAt: today15,
        endAt: addDaysAt(0, 15, 30),
        recurrence: "none",
        reminder: "1h_before",
        createdAt: createdOld,
        updatedAt: today15,
        showInTasks: true,
        showInCalendar: true,
      },
      {
        id: createId("item"),
        leadId: "lead_8",
        recordType: "task",
        type: "proposal",
        title: "Wysłać case studies",
        description: "Dwa case studies pod e-commerce.",
        status: "todo",
        priority: "high",
        scheduledAt: twoDaysAgo12,
        startAt: "",
        endAt: "",
        recurrence: "none",
        reminder: "1h_before",
        createdAt: createdOld,
        updatedAt: twoDaysAgo12,
        showInTasks: true,
        showInCalendar: true,
      },
      {
        id: createId("item"),
        leadId: null,
        leadLabel: "Wewnętrzne",
        recordType: "task",
        type: "task",
        title: "Przejrzeć pipeline tygodnia",
        description: "Sprawdzić wszystkie zaległe follow-upy.",
        status: "todo",
        priority: "medium",
        scheduledAt: inThreeDays10,
        startAt: "",
        endAt: "",
        recurrence: "none",
        reminder: "none",
        createdAt: createdOld,
        updatedAt: inThreeDays10,
        showInTasks: true,
        showInCalendar: false,
      },
    ],
  }
}

